// <auto-generated />
using System;
using Dormitory.DormitoryModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dormitory.Migrations
{
    [DbContext(typeof(DormitoryDbContext))]
    [Migration("20260330093957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Dormitory.DormitoryModels.Admin", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1) unsigned")
                        .HasDefaultValueSql("'1'")
                        .HasComment("type in c# is boolean (1 = active, 0 = disabled)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasComment("hashed password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Signature")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .HasColumnType("enum('นาย','นางสาว','นาง')");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "Phone")
                        .IsUnique();

                    b.ToTable("Admin", t =>
                        {
                            t.HasComment("Stores administrator account information for managing and maintaining the system.");
                        });
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Apartment", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LineId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LineID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("PaymentDueEnd")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasComment("Payment end date.");

                    b.Property<byte>("PaymentDueStart")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasComment("Payment start date.");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique()
                        .HasDatabaseName("Email1");

                    b.HasIndex(new[] { "LineId" }, "LineID")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "Phone")
                        .IsUnique()
                        .HasDatabaseName("Phone1");

                    b.ToTable("Apartment", t =>
                        {
                            t.HasComment("Collect general information about the dormitory.");
                        });
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Constant", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("enum('service','utility','facility','maintenance','penalty','property','other')");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Constant");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Contract", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(20,3) unsigned");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<uint?>("InitialElectricUnit")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("InitialWaterUnit")
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(20,3) unsigned");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("save a name of file");

                    b.Property<uint>("RoomId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Reserved','cancle','Active','Terminated','Expired')");

                    b.Property<uint?>("TenantId")
                        .HasColumnType("int(10) unsigned");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomId" }, "RoomIdTContract");

                    b.HasIndex(new[] { "TenantId" }, "TenantIdTContract");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Document", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint>("AdminId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminId" }, "AdminIdTDocument");

                    b.ToTable("Document", t =>
                        {
                            t.HasComment("Stores dormitory-related documents such as rental contracts, invoices, and payment records.\r\n");
                        });
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Parcel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PickupDate")
                        .HasColumnType("date");

                    b.Property<string>("Recipient")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RoomId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("ShippingCompany")
                        .HasColumnType("enum('thaipost','kerry','j&t','shopee','lazada','dhl','other')");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Type")
                        .HasColumnType("enum('box','pack','other')");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomId" }, "RoomIdTParcel");

                    b.ToTable("Parcel");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Payment", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal?>("AdditionalCost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("AdditionalDetail")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<uint>("AdminId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint>("ContractId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal?>("DiscountCost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("DiscountDetail")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("ElectricalPricePerUnit")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<decimal?>("FurnitureCost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<decimal?>("InternetCost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<decimal?>("LaundryCost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("RoomRate")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('paid','unpaid')")
                        .HasDefaultValueSql("'unpaid'");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<decimal?>("WaterPricePerUnit")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminId" }, "AdminIdTPayment");

                    b.HasIndex(new[] { "ContractId" }, "ContractIdTPayment");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Permission", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint>("AdminId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint>("ApartmentId")
                        .HasColumnType("int(10) unsigned");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AdminId" }, "AdminIdTPermission");

                    b.HasIndex(new[] { "ApartmentId" }, "ApartmentIdTPermission");

                    b.ToTable("Permission", t =>
                        {
                            t.HasComment("Stores permission data that defines access rights (in the future : actions allowed for each role or user) in the system.");
                        });
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Request", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateOnly?>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)");

                    b.Property<bool?>("IsTenantCost")
                        .HasColumnType("tinyint(1)")
                        .HasComment("in c# is boolean (0 = false, 1 = true)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date");

                    b.Property<uint>("RoomId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','finish','cancel')")
                        .HasDefaultValueSql("'pending'");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("enum('fix','clean','leave','other')");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomId" }, "RoomIdTRequest");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Room", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Building")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Floor")
                        .HasColumnType("enum('1','2','3','4','5')");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('available','occupied','reserved','close','delete')")
                        .HasDefaultValueSql("'available'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Room", t =>
                        {
                            t.HasComment("Stores apartment room information including room number, floor, room type, and current room status.");
                        });
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Tenant", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AltName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AltPhone")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AltRelationship")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<uint?>("InternetDeviceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValueSql("'0'");

                    b.Property<bool?>("IsLaundryService")
                        .HasColumnType("tinyint(1)")
                        .HasComment("in c# = boolean (0 = false, 1 = true)");

                    b.Property<string>("KeyCard1")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("KeyCard2")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("KeyCard3")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LineId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NickName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Nin")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("save a name of file");

                    b.Property<string>("Title")
                        .HasColumnType("enum('นาย','นาง','นางสาว','เด็กชาย','เด็กหญิง')");

                    b.Property<string>("VehicleDetail1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VehicleDetail2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VehicleNum1")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("VehicleNum2")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AltPhone" }, "AltPhone")
                        .IsUnique();

                    b.HasIndex(new[] { "Nin" }, "Nin")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "Phone")
                        .IsUnique()
                        .HasDatabaseName("Phone2");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.UtilityMeter", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("ChangeElectricityMeterEnd")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("ChangeElectricityMeterStart")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("ChangeWaterMeterEnd")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("ChangeWaterMeterStart")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("ElectricityUnit")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<uint>("RoomId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint?>("WaterUnit")
                        .HasColumnType("int(10) unsigned");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomId" }, "RoomIdTUtilityMeter");

                    b.ToTable("UtilityMeter");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Contract", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Room", "Room")
                        .WithMany("Contract")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("RoomIdTContract");

                    b.HasOne("Dormitory.DormitoryModels.Tenant", "Tenant")
                        .WithMany("Contract")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("TenantIdTContract");

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Document", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Admin", "Admin")
                        .WithMany("Document")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("AdminIdTDocument");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Parcel", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Room", "Room")
                        .WithMany("Parcel")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("RoomIdTParcel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Payment", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Admin", "Admin")
                        .WithMany("Payment")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("AdminIdTPayment");

                    b.HasOne("Dormitory.DormitoryModels.Contract", "Contract")
                        .WithMany("Payment")
                        .HasForeignKey("ContractId")
                        .IsRequired()
                        .HasConstraintName("ContractIdTPayment");

                    b.Navigation("Admin");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Permission", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Admin", "Admin")
                        .WithMany("Permission")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("AdminIdTPermission");

                    b.HasOne("Dormitory.DormitoryModels.Apartment", "Apartment")
                        .WithMany("Permission")
                        .HasForeignKey("ApartmentId")
                        .IsRequired()
                        .HasConstraintName("ApartmentIdTPermission");

                    b.Navigation("Admin");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Request", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Room", "Room")
                        .WithMany("Request")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("RoomIdTRequest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.UtilityMeter", b =>
                {
                    b.HasOne("Dormitory.DormitoryModels.Room", "Room")
                        .WithMany("UtilityMeter")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("RoomIdTUtilityMeter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Admin", b =>
                {
                    b.Navigation("Document");

                    b.Navigation("Payment");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Apartment", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Contract", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Room", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Parcel");

                    b.Navigation("Request");

                    b.Navigation("UtilityMeter");
                });

            modelBuilder.Entity("Dormitory.DormitoryModels.Tenant", b =>
                {
                    b.Navigation("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
